name: Rotki Development Builds

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - build

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  PYTHON_MACOS: 11

jobs:
  build-macos:
    name: 'Build macOS binary'
    env:
      CI: true
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MACOS_BUILD_ARCH: 'universal2'
      ARCHFLAGS: '-arch arm64 -arch x86_64'
      _PYTHON_HOST_PLATFORM: macosx-10.9-universal2
      MACOSX_DEPLOYMENT_TARGET: 10.9
      CMAKE_OSX_ARCHITECTURES: 'x86_64;arm64'
    environment: macos_sign
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Load env
        uses: rotki/action-env@v2
        with:
          env_file: .github/.env.ci
      - name: Checkout libffi
        uses: actions/checkout@v4
        with:
          repository: libffi/libffi
          path: libffi
          ref: v3.4.2
      - name: Install libffi build tools
        run: brew install autoconf automake libtool pkg-config
      - name: Build universal libbfi (required by coincurve)
        run: |
          brew uninstall --ignore-dependencies libffi || true
          echo "::group::Autogen"
          ./autogen.sh
          echo "::endgroup::"
          echo "::group::arm64"
          ./configure --host=aarch64-apple-darwin CC='gcc -arch arm64' CXX='g++ -arch arm64'
          make
          mkdir ../ffi
          cp -R aarch64-apple-darwin ../ffi/
          echo "::endgroup::"
          echo "::group::x86_64"
          make clean
          ./configure --host=x86_64-apple-darwin CC='gcc -arch x86_64' CXX='g++ -arch x86_64'
          make
          echo "::endgroup::"
          echo "::group::install"
          lipo -create -output x86_64-apple-darwin/.libs/libffi.8.dylib x86_64-apple-darwin/.libs/libffi.8.dylib ../ffi/aarch64-apple-darwin/.libs/libffi.8.dylib
          lipo -create -output x86_64-apple-darwin/.libs/libffi.a x86_64-apple-darwin/.libs/libffi.a ../ffi/aarch64-apple-darwin/.libs/libffi.a
          lipo -create -output x86_64-apple-darwin/.libs/libffi_convenience.a x86_64-apple-darwin/.libs/libffi_convenience.a ../ffi/aarch64-apple-darwin/.libs/libffi_convenience.a
          lipo -archs x86_64-apple-darwin/.libs/libffi.8.dylib
          make install
          echo "::endgroup::"
        working-directory: libffi
      - name: Add rust target for building deps
        run: rustup target add aarch64-apple-darwin
      - name: Cache python pkg
        uses: actions/cache@v4
        with:
          path: ~/python*.pkg
          key: ${{ runner.os }}-python-${{ env.PYTHON_VERSION }}-${{ env.PYTHON_MACOS }}
      - name: Cache python dependencies
        uses: actions/cache@v4
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up python
        run: packaging/setup-macos-python.sh ${{ env.PYTHON_VERSION }} ${{ env.PYTHON_MACOS }}
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.pnpm-cache.outputs.STORE_PATH }}
            frontend/app/components.d.ts
            ~/Library/Caches/Cypress
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Package
        id: packaging
        run: |
          echo "::group::packaging dependencies"
          pip3 install --upgrade uv
          pip3 install virtualenv
          python3 -m virtualenv ~/venv
          source ~/venv/bin/activate
          uv pip install -r requirements_packaging.txt
          echo "::endgroup::"
          ./package.py --build full
        env:
          CERTIFICATE_OSX_APPLICATION: ${{ secrets.CERTIFICATE_OSX_APPLICATION }}
          CSC_KEY_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
          IDENTITY: ${{ secrets.IDENTITY }}
          APPLEID: ${{ secrets.APPLEID }}
          APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
      - name: Upload files (arm64)
        uses: actions/upload-artifact@v4
        with:
          name: macos-app-arm64
          path: |
            dist/rotki-darwin_arm64*.dmg
            dist/rotki-darwin_arm64*.dmg.sha512
      - name: Upload files (x86_64)
        uses: actions/upload-artifact@v4
        with:
          name: macos-app-x64
          path: |
            dist/rotki-darwin_x64*.dmg
            dist/rotki-darwin_x64*.dmg.sha512
      - name: Upload colibri files
        uses: actions/upload-artifact@v4
        with:
          name: macos-colibri
          path: |
            dist/colibri
  notify:
    name: 'Success check'
    if: ${{ always() }}
    needs: ['build-macos' ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Check if any task failed
        run: |
          pip install requests

          data=($(echo "${{ toJSON(needs.*.result) }}" | sed 's/[][,]//g'))
          for i in "${data[@]}"
          do
            if [[ $i == "failure" ]]; then
                ./.github/scripts/notifier.py --webhook ${{ secrets.WEBHOOK }} --run-id ${{ github.run_id }}
                exit 1;
            fi
          done